const { SlashCommandBuilder, EmbedBuilder } = require("discord.js");

const gifleGifs = [
  "https://media.tenor.com/Sv8LQZAoQmgAAAAM/chainsaw-man-csm.gif",
  "https://media.tenor.com/xqxgr-wfiJMAAAAM/anime.gif",
  "https://tenor.com/fr/view/slap-gif-20126850",
  "https://tenor.com/fr/view/slap-gif-20126989",
  "https://media.tenor.com/E3OW-MYYum0AAAAM/no-angry.gif",
  "https://media.tenor.com/1-1M4PZpYcMAAAAM/tsuki-tsuki-ga.gif",
  "https://tenor.com/fr/search/handa-seishuu-gifs",
  "https://media.tenor.com/2J2Leu-RoVsAAAAM/eureka-7-eureka-seven.gif",
  "https://media.tenor.com/24XQteNk3K0AAAAM/anime-girls.gif",
  "https://media.tenor.com/m14m8vGLFugAAAAM/asobi-asobase-anime.gif",
  "https://media.tenor.com/umXpRY6EYmgAAAAM/mushokutensei-slap.gif",
  "https://media.tenor.com/Fs0QfuMH-4UAAAAM/anime-manga.gif",
  "https://media.tenor.com/Ao52XTMY1RcAAAAM/slap.gif",
  "https://media.tenor.com/-nUvNvpdFJYAAAAM/working-wagnaria.gif",
  "https://media.tenor.com/NMvI03LMTzIAAAAM/mushoku-tensei-boy-hit-girl.gif",
  "https://media.tenor.com/-wfr09tbkwcAAAAM/discord-anime.gif",
  "https://media.tenor.com/DTVNVJrDdJIAAAAM/my-collection-anime.gif",
  "https://media.tenor.com/j6UWDrX6ZrwAAAAM/arima-ichika-ichika.gif",
  "https://media.tenor.com/UDo0WPttiRsAAAAM/bunny-girl-slap.gif",
  "https://media.tenor.com/bHE5Txlp5-8AAAAM/slap-butts-anime.gif",
  "https://media.tenor.com/DTVNVJrDdJIAAAAM/my-collection-anime.gif",
  "https://media.tenor.com/7xFcP1KWjY0AAAAM/no.gif",
  "https://media.tenor.com/Ws6Dm1ZW_vMAAAAM/girl-slap.gif",
  "https://media.tenor.com/WWE1BxoPzv4AAAAM/my-hero-academia-anime.gif",
  "https://media.tenor.com/HTHoXnBc400AAAAM/in-your-face-slap.gif",
  "https://media.tenor.com/24XQteNk3K0AAAAM/anime-girls.gif",
  "https://media.tenor.com/TGO7qG_lEDQAAAAM/ogata-rina-white-album-anime.gif",
  "https://media.tenor.com/L0fsdBYmh_wAAAAM/kokoro-connect-slap-anime.gif",
  "https://media.tenor.com/Sv8LQZAoQmgAAAAM/chainsaw-man-csm.gif",
  "https://media.tenor.com/xqxgr-wfiJMAAAAM/anime.gif",
  "https://tenor.com/fr/view/slap-gif-20126850",
  "https://tenor.com/fr/view/slap-gif-20126989",
  "https://media.tenor.com/E3OW-MYYum0AAAAM/no-angry.gif",
  "https://media.tenor.com/1-1M4PZpYcMAAAAM/tsuki-tsuki-ga.gif",
  "https://tenor.com/fr/search/handa-seishuu-gifs",
  "https://media.tenor.com/2J2Leu-RoVsAAAAM/eureka-7-eureka-seven.gif",
  "https://media.tenor.com/24XQteNk3K0AAAAM/anime-girls.gif",
  "https://media.tenor.com/m14m8vGLFugAAAAM/asobi-asobase-anime.gif",
  "https://media.tenor.com/umXpRY6EYmgAAAAM/mushokutensei-slap.gif",
  "https://media.tenor.com/Fs0QfuMH-4UAAAAM/anime-manga.gif",
  "https://media.tenor.com/Ao52XTMY1RcAAAAM/slap.gif",
  "https://media.tenor.com/-nUvNvpdFJYAAAAM/working-wagnaria.gif",
  "https://media.tenor.com/NMvI03LMTzIAAAAM/mushoku-tensei-boy-hit-girl.gif",
  "https://media.tenor.com/-wfr09tbkwcAAAAM/discord-anime.gif",
  "https://media.tenor.com/DTVNVJrDdJIAAAAM/my-collection-anime.gif",
  "https://media.tenor.com/j6UWDrX6ZrwAAAAM/arima-ichika-ichika.gif",
  "https://media.tenor.com/UDo0WPttiRsAAAAM/bunny-girl-slap.gif",
  "https://media.tenor.com/bHE5Txlp5-8AAAAM/slap-butts-anime.gif",
  "https://media.tenor.com/DTVNVJrDdJIAAAAM/my-collection-anime.gif",
  "https://media.tenor.com/7xFcP1KWjY0AAAAM/no.gif",
  "https://media.tenor.com/Ws6Dm1ZW_vMAAAAM/girl-slap.gif",
  "https://media.tenor.com/WWE1BxoPzv4AAAAM/my-hero-academia-anime.gif",
  "https://media.tenor.com/HTHoXnBc400AAAAM/in-your-face-slap.gif",
  "https://media.tenor.com/24XQteNk3K0AAAAM/anime-girls.gif",
  "https://media.tenor.com/TGO7qG_lEDQAAAAM/ogata-rina-white-album-anime.gif",
  "https://media.tenor.com/L0fsdBYmh_wAAAAM/kokoro-connect-slap-anime.gif",
  "https://media.tenor.com/Sv8LQZAoQmgAAAAM/chainsaw-man-csm.gif",
  "https://media.tenor.com/xqxgr-wfiJMAAAAM/anime.gif",
  "https://tenor.com/fr/view/slap-gif-20126850",
  "https://tenor.com/fr/view/slap-gif-20126989",
  "https://media.tenor.com/E3OW-MYYum0AAAAM/no-angry.gif",
  "https://media.tenor.com/1-1M4PZpYcMAAAAM/tsuki-tsuki-ga.gif",
  "https://tenor.com/fr/search/handa-seishuu-gifs",
  "https://media.tenor.com/2J2Leu-RoVsAAAAM/eureka-7-eureka-seven.gif",
  "https://media.tenor.com/24XQteNk3K0AAAAM/anime-girls.gif",
  "https://media.tenor.com/m14m8vGLFugAAAAM/asobi-asobase-anime.gif",
  "https://media.tenor.com/umXpRY6EYmgAAAAM/mushokutensei-slap.gif",
  "https://media.tenor.com/Fs0QfuMH-4UAAAAM/anime-manga.gif",
  "https://media.tenor.com/Ao52XTMY1RcAAAAM/slap.gif",
  "https://media.tenor.com/-nUvNvpdFJYAAAAM/working-wagnaria.gif",
  "https://media.tenor.com/NMvI03LMTzIAAAAM/mushoku-tensei-boy-hit-girl.gif",
  "https://media.tenor.com/-wfr09tbkwcAAAAM/discord-anime.gif",
  "https://media.tenor.com/DTVNVJrDdJIAAAAM/my-collection-anime.gif",
  "https://media.tenor.com/j6UWDrX6ZrwAAAAM/arima-ichika-ichika.gif",
  "https://media.tenor.com/UDo0WPttiRsAAAAM/bunny-girl-slap.gif",
  "https://media.tenor.com/bHE5Txlp5-8AAAAM/slap-butts-anime.gif",
  "https://media.tenor.com/DTVNVJrDdJIAAAAM/my-collection-anime.gif",
  "https://media.tenor.com/7xFcP1KWjY0AAAAM/no.gif",
  "https://media.tenor.com/Ws6Dm1ZW_vMAAAAM/girl-slap.gif",
  "https://media.tenor.com/WWE1BxoPzv4AAAAM/my-hero-academia-anime.gif",
  "https://media.tenor.com/HTHoXnBc400AAAAM/in-your-face-slap.gif",
  "https://media.tenor.com/24XQteNk3K0AAAAM/anime-girls.gif",
  "https://media.tenor.com/TGO7qG_lEDQAAAAM/ogata-rina-white-album-anime.gif",
  "https://media.tenor.com/L0fsdBYmh_wAAAAM/kokoro-connect-slap-anime.gif",
  "https://media.tenor.com/Sv8LQZAoQmgAAAAM/chainsaw-man-csm.gif",
  "https://media.tenor.com/xqxgr-wfiJMAAAAM/anime.gif",
  "https://tenor.com/fr/view/slap-gif-20126850",
  "https://tenor.com/fr/view/slap-gif-20126989",
  "https://media.tenor.com/E3OW-MYYum0AAAAM/no-angry.gif",
  "https://media.tenor.com/1-1M4PZpYcMAAAAM/tsuki-tsuki-ga.gif",
  "https://tenor.com/fr/search/handa-seishuu-gifs",
  "https://media.tenor.com/2J2Leu-RoVsAAAAM/eureka-7-eureka-seven.gif",
  "https://media.tenor.com/24XQteNk3K0AAAAM/anime-girls.gif",
  "https://media.tenor.com/m14m8vGLFugAAAAM/asobi-asobase-anime.gif",
  "https://media.tenor.com/umXpRY6EYmgAAAAM/mushokutensei-slap.gif",
  "https://media.tenor.com/Fs0QfuMH-4UAAAAM/anime-manga.gif",
  "https://media.tenor.com/Ao52XTMY1RcAAAAM/slap.gif",
  "https://media.tenor.com/-nUvNvpdFJYAAAAM/working-wagnaria.gif",
  "https://media.tenor.com/NMvI03LMTzIAAAAM/mushoku-tensei-boy-hit-girl.gif",
  "https://media.tenor.com/-wfr09tbkwcAAAAM/discord-anime.gif",
  "https://media.tenor.com/DTVNVJrDdJIAAAAM/my-collection-anime.gif",
  "https://media.tenor.com/j6UWDrX6ZrwAAAAM/arima-ichika-ichika.gif",
  "https://media.tenor.com/UDo0WPttiRsAAAAM/bunny-girl-slap.gif",
  "https://media.tenor.com/bHE5Txlp5-8AAAAM/slap-butts-anime.gif",
  "https://media.tenor.com/DTVNVJrDdJIAAAAM/my-collection-anime.gif",
  "https://media.tenor.com/7xFcP1KWjY0AAAAM/no.gif",
  "https://media.tenor.com/Ws6Dm1ZW_vMAAAAM/girl-slap.gif",
  "https://media.tenor.com/WWE1BxoPzv4AAAAM/my-hero-academia-anime.gif",
  "https://media.tenor.com/HTHoXnBc400AAAAM/in-your-face-slap.gif",
  "https://media.tenor.com/24XQteNk3K0AAAAM/anime-girls.gif",
  "https://media.tenor.com/TGO7qG_lEDQAAAAM/ogata-rina-white-album-anime.gif",
  "https://media.tenor.com/L0fsdBYmh_wAAAAM/kokoro-connect-slap-anime.gif",
  "https://media.tenor.com/Sv8LQZAoQmgAAAAM/chainsaw-man-csm.gif",
  "https://media.tenor.com/xqxgr-wfiJMAAAAM/anime.gif",
  "https://tenor.com/fr/view/slap-gif-20126850",
  "https://tenor.com/fr/view/slap-gif-20126989",
  "https://media.tenor.com/E3OW-MYYum0AAAAM/no-angry.gif",
  "https://media.tenor.com/1-1M4PZpYcMAAAAM/tsuki-tsuki-ga.gif",
  "https://tenor.com/fr/search/handa-seishuu-gifs",
  "https://media.tenor.com/2J2Leu-RoVsAAAAM/eureka-7-eureka-seven.gif",
  "https://media.tenor.com/24XQteNk3K0AAAAM/anime-girls.gif",
  "https://media.tenor.com/m14m8vGLFugAAAAM/asobi-asobase-anime.gif",
  "https://media.tenor.com/umXpRY6EYmgAAAAM/mushokutensei-slap.gif",
  "https://media.tenor.com/Fs0QfuMH-4UAAAAM/anime-manga.gif",
  "https://media.tenor.com/Ao52XTMY1RcAAAAM/slap.gif",
  "https://media.tenor.com/-nUvNvpdFJYAAAAM/working-wagnaria.gif",
  "https://media.tenor.com/NMvI03LMTzIAAAAM/mushoku-tensei-boy-hit-girl.gif",
  "https://media.tenor.com/-wfr09tbkwcAAAAM/discord-anime.gif",
  "https://media.tenor.com/DTVNVJrDdJIAAAAM/my-collection-anime.gif",
  "https://media.tenor.com/j6UWDrX6ZrwAAAAM/arima-ichika-ichika.gif",
  "https://media.tenor.com/UDo0WPttiRsAAAAM/bunny-girl-slap.gif",
  "https://media.tenor.com/bHE5Txlp5-8AAAAM/slap-butts-anime.gif",
  "https://media.tenor.com/DTVNVJrDdJIAAAAM/my-collection-anime.gif",
  "https://media.tenor.com/7xFcP1KWjY0AAAAM/no.gif",
  "https://media.tenor.com/Ws6Dm1ZW_vMAAAAM/girl-slap.gif",
  "https://media.tenor.com/WWE1BxoPzv4AAAAM/my-hero-academia-anime.gif",
  "https://media.tenor.com/HTHoXnBc400AAAAM/in-your-face-slap.gif",
  "https://media.tenor.com/24XQteNk3K0AAAAM/anime-girls.gif",
  "https://media.tenor.com/TGO7qG_lEDQAAAAM/ogata-rina-white-album-anime.gif",
  "https://media.tenor.com/L0fsdBYmh_wAAAAM/kokoro-connect-slap-anime.gif",
  "https://media.tenor.com/Sv8LQZAoQmgAAAAM/chainsaw-man-csm.gif",
  "https://media.tenor.com/xqxgr-wfiJMAAAAM/anime.gif",
  "https://tenor.com/fr/view/slap-gif-20126850",
  "https://tenor.com/fr/view/slap-gif-20126989",
  "https://media.tenor.com/E3OW-MYYum0AAAAM/no-angry.gif",
  "https://media.tenor.com/1-1M4PZpYcMAAAAM/tsuki-tsuki-ga.gif",
  "https://tenor.com/fr/search/handa-seishuu-gifs",
  "https://media.tenor.com/2J2Leu-RoVsAAAAM/eureka-7-eureka-seven.gif",
  "https://media.tenor.com/24XQteNk3K0AAAAM/anime-girls.gif",
  "https://media.tenor.com/m14m8vGLFugAAAAM/asobi-asobase-anime.gif",
  "https://media.tenor.com/umXpRY6EYmgAAAAM/mushokutensei-slap.gif",
  "https://media.tenor.com/Fs0QfuMH-4UAAAAM/anime-manga.gif",
  "https://media.tenor.com/Ao52XTMY1RcAAAAM/slap.gif",
  "https://media.tenor.com/-nUvNvpdFJYAAAAM/working-wagnaria.gif",
  "https://media.tenor.com/NMvI03LMTzIAAAAM/mushoku-tensei-boy-hit-girl.gif",
  "https://media.tenor.com/-wfr09tbkwcAAAAM/discord-anime.gif",
  "https://media.tenor.com/DTVNVJrDdJIAAAAM/my-collection-anime.gif",
  "https://media.tenor.com/j6UWDrX6ZrwAAAAM/arima-ichika-ichika.gif",
  "https://media.tenor.com/UDo0WPttiRsAAAAM/bunny-girl-slap.gif",
  "https://media.tenor.com/bHE5Txlp5-8AAAAM/slap-butts-anime.gif",
  "https://media.tenor.com/DTVNVJrDdJIAAAAM/my-collection-anime.gif",
  "https://media.tenor.com/7xFcP1KWjY0AAAAM/no.gif",
  "https://media.tenor.com/Ws6Dm1ZW_vMAAAAM/girl-slap.gif",
  "https://media.tenor.com/WWE1BxoPzv4AAAAM/my-hero-academia-anime.gif",
  "https://media.tenor.com/HTHoXnBc400AAAAM/in-your-face-slap.gif",
  "https://media.tenor.com/24XQteNk3K0AAAAM/anime-girls.gif",
  "https://media.tenor.com/TGO7qG_lEDQAAAAM/ogata-rina-white-album-anime.gif",
  "https://media.tenor.com/L0fsdBYmh_wAAAAM/kokoro-connect-slap-anime.gif",
];

const gifle = {
  data: new SlashCommandBuilder()
    .setName("gifle")
    .setDescription("\u2728 Donne une gifle à un membre avec style 👋")
    .addUserOption((option) =>
      option
        .setName("membre")
        .setDescription("\u2728 La personne à gifler")
        .setRequired(true),
    ),

  async executeCommand(client, interaction) {
    const cible = interaction.options.getUser("membre");
    const auteur = interaction.user;

    if (cible.id === auteur.id)
      return interaction.reply({
        content: "Tu ne peux pas te gifler toi-même 😅",
        ephemeral: true,
      });

    const gif = gifleGifs[Math.floor(Math.random() * gifleGifs.length)];

    const embed = new EmbedBuilder()
      .setColor("#FF4500")
      .setTitle("👋 Gifle reçue !")
      .setDescription(
        `**${auteur.username}** donne une gifle à **${cible.username}** ! Ouille ! 👋🔥`,
      )
      .setImage(gif)
      .setFooter({ text: "Commande gifle par Mrkevin_BOT" })
      .setTimestamp();

    await interaction.reply({ embeds: [embed] });
  },

  settings: {
    module: "general",
    enabled: true,
  },
};

module.exports = { default: gifle };


